version: '3'
services:
  db:
    image: mysql:5.7
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=5w0rd
      - MYSQL_DATABASE=sword
      - MYSQL_USER=sword_test
      - MYSQL_PASSWORD=5w0rd
    networks:
      - mynet
      
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - mynet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: 
      "on-failure"
    depends_on:
      db:
        condition: service_started
      nats:
        condition: service_started
    networks:
      - mynet

networks:
  mynet:
    driver: bridge